### ISSUE TITLE
[doc] Stempel: no information how to reimplement the analyzer

### ISSUE THREAD

**Issue by merito** [elastic/elasticsearch-analysis-stempel#43]
Hi,

I would like to reimplement the analyzer, for example add my synonyms, but there is no available filter list, for official language analyzers you can find it here - [elastic documentation](https://www.elastic.co/guide/en/elasticsearch/reference/current/analysis-lang-analyzer.html#english-analyzer). Could you add this to the docs?

**Comment by mod3st** [comment]
+1

**Comment by jeanbelhache** [comment]
+1

**Comment by dadoonet** [comment]
This issue was moved to elastic/elasticsearch#13150
