### ISSUE TITLE
Adding ascii folding for Polish stemming

### ISSUE THREAD

**Issue by janowitz** [elastic/elasticsearch-analysis-stempel#46]
I'm quite new to elasticsearch but I got this useful plugin working. Unfortunately I am not able to add asciifolding to it, no matter if I use preserve_original or not.
Is there a possibility to get this plugin working along with asciifolding?

**Comment by dadoonet** [comment]
May be you want to have 2 analyzers? So you should use multifield?

BTW, please ask your questions on discuss.elastic.co. You will get a lot more people reading your question and help!
