### ISSUE TITLE
How to support polish English

### ISSUE THREAD

**Issue by danielludan** [elastic/elasticsearch-analysis-stempel#47]
Thanks for providing us so easy-to-use analyzer. Just tested it and it seems don't work well for English see my analysis result as below:

I also checked your test case and it seems default support for words kwiaty kwć canona ć, sorry for that I can't recognize these words from what language.

{
:   "tokens":
:   [
:   :   {
:   :   :   "token":"workers",
:   :   :   "start_offset":0,
:   :   :   "end_offset":7,
:   :   :   "type":"<ALPHANUM>",
:   :   :   "position":1
:   :   },
:   :   {
:   :   :   "token":"worker",
:   :   :   "start_offset":8,
:   :   :   "end_offset":14,
:   :   :   "type":"<ALPHANUM>",
:   :   :   "position":2
:   :   },
:   :   {
:   :   :   "token":"thoughć",
:   :   :   "start_offset":15,
:   :   :   "end_offset":22,
:   :   :   "type":"<ALPHANUM>",
:   :   :   "position":3
:   :   },
:   :   {
:   :   :   "token":"think",
:   :   :   "start_offset":23,
:   :   :   "end_offset":28,
:   :   :   "type":"<ALPHANUM>",
:   :   :   "position":4
:   :   }
:   ]
}

**Comment by danielludan** [comment]
Not sure if I am thinking correctly. I treat this tool as a stem analyzer which can help to me to analyze different words with same stem into same word, like workers and worker should be both treated as worker, think and thought should be both treated as think. Is there anything I think incorrectly? 

Thanks!

**Comment by dadoonet** [comment]
This plugin helps to deal with polish.

Use a stemmer instead. Define your own analyzer with an english stemmer.
